[phases.setup]
    nixPkgs = ['python311']

[phases.install]
    cmds = [
        'python3 -m pip install --upgrade pip',
        'python3 -m pip install -r requirements.txt',
        'python3 nltk_data_download.py'
    ]

[start]
    cmd = 'gunicorn --chdir web app:app --timeout 120'